version: '3'
services:
  nextjs:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.next 
      - /usr/src/app/node_modules  # ホストとコンテナ間で node_modules を分離
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "dev"]  
